// Generated by tools/build-content.mjs; browser-safe breed registry.
import breedGinger from './breeds/ginger'
import breedTabby from './breeds/tabby'
import breedGrey from './breeds/grey'
import breedBlack from './breeds/black'
import breedWhite from './breeds/white'
import breedCream from './breeds/cream'
import breedCalico from './breeds/calico'
import breedTuxedo from './breeds/tuxedo'
import breedSiamese from './breeds/siamese'
import breedChocolate from './breeds/chocolate'
import breedCinnamon from './breeds/cinnamon'
import breedSilver from './breeds/silver'
import breedSmoke from './breeds/smoke'
import breedTortoiseshell from './breeds/tortoiseshell'
import breedRagdoll from './breeds/ragdoll'
import breedBengal from './breeds/bengal'
import breedLynx from './breeds/lynx'
import breedNebula from './breeds/nebula'
import breedRussianBlue from './breeds/russian-blue'
import breedBlueCream from './breeds/blue-cream'
import breedCalicoVoid from './breeds/calico-void'
import breedCopperBengal from './breeds/copper-bengal'
import breedGhost from './breeds/ghost'
import breedGoldenGlitch from './breeds/golden-glitch'
import breedMoonSmoke from './breeds/moon-smoke'
import breedSnowshoe from './breeds/snowshoe'
import breedStarpoint from './breeds/starpoint'
import breedTigerTabby from './breeds/tiger-tabby'
import type { Breed } from './types'

// breeds definitions in pinned order; engines apply runtime eligibility.
export const BREEDS: readonly Breed[] = [
  breedGinger,
  breedTabby,
  breedGrey,
  breedBlack,
  breedWhite,
  breedCream,
  breedCalico,
  breedTuxedo,
  breedSiamese,
  breedChocolate,
  breedCinnamon,
  breedSilver,
  breedSmoke,
  breedTortoiseshell,
  breedRagdoll,
  breedBengal,
  breedLynx,
  breedNebula,
  breedRussianBlue,
  breedBlueCream,
  breedCalicoVoid,
  breedCopperBengal,
  breedGhost,
  breedGoldenGlitch,
  breedMoonSmoke,
  breedSnowshoe,
  breedStarpoint,
  breedTigerTabby,
]
