// Generated by tools/build-content.mjs: add a file to a content folder, then rerun it.
import breedGinger from './breeds/ginger'
import breedTabby from './breeds/tabby'
import breedGrey from './breeds/grey'
import breedBlack from './breeds/black'
import breedWhite from './breeds/white'
import breedCream from './breeds/cream'
import breedCalico from './breeds/calico'
import breedTuxedo from './breeds/tuxedo'
import breedSiamese from './breeds/siamese'
import breedChocolate from './breeds/chocolate'
import breedCinnamon from './breeds/cinnamon'
import breedSilver from './breeds/silver'
import breedSmoke from './breeds/smoke'
import breedTortoiseshell from './breeds/tortoiseshell'
import breedRagdoll from './breeds/ragdoll'
import breedBengal from './breeds/bengal'
import breedLynx from './breeds/lynx'
import breedNebula from './breeds/nebula'
import breedRussianBlue from './breeds/russian-blue'
import breedBlueCream from './breeds/blue-cream'
import breedCalicoVoid from './breeds/calico-void'
import breedCopperBengal from './breeds/copper-bengal'
import breedGhost from './breeds/ghost'
import breedGoldenGlitch from './breeds/golden-glitch'
import breedMoonSmoke from './breeds/moon-smoke'
import breedSnowshoe from './breeds/snowshoe'
import breedStarpoint from './breeds/starpoint'
import breedTigerTabby from './breeds/tiger-tabby'
import moveGroom from './moves/groom'
import moveHop from './moves/hop'
import moveLoaf from './moves/loaf'
import moveNapCurl from './moves/nap-curl'
import movePounce from './moves/pounce'
import moveSit from './moves/sit'
import moveStretch from './moves/stretch'
import moveTrot from './moves/trot'
import moveWalk from './moves/walk'
import moveZoomies from './moves/zoomies'
import movePipeLounge from './moves/pipe-lounge'
import moveTowerPerch from './moves/tower-perch'
import moveTunnelDash from './moves/tunnel-dash'
import moveProwl from './moves/prowl'
import worldBackyard from './worlds/backyard'
import worldRooftops from './worlds/rooftops'
import worldBeachPier from './worlds/beach-pier'
import worldNeonAlley from './worlds/neon-alley'
import worldSnowyCabin from './worlds/snowy-cabin'
import worldSpaceStation from './worlds/space-station'
import catCaptainWhiskers from './cats/captain-whiskers'
import catAdmiralClaw from './cats/admiral-claw'
import catBoo from './cats/boo'
import catMerlinMeow from './cats/merlin-meow'
import catNova from './cats/nova'
import catPixel from './cats/pixel'
import type { Breed, Move, World, NamedCat } from './types'

export const BREEDS: readonly Breed[] = [
  breedGinger,
  breedTabby,
  breedGrey,
  breedBlack,
  breedWhite,
  breedCream,
  breedCalico,
  breedTuxedo,
  breedSiamese,
  breedChocolate,
  breedCinnamon,
  breedSilver,
  breedSmoke,
  breedTortoiseshell,
  breedRagdoll,
  breedBengal,
  breedLynx,
  breedNebula,
  breedRussianBlue,
  breedBlueCream,
  breedCalicoVoid,
  breedCopperBengal,
  breedGhost,
  breedGoldenGlitch,
  breedMoonSmoke,
  breedSnowshoe,
  breedStarpoint,
  breedTigerTabby,
]
export const MOVES: readonly Move[] = [
  moveGroom,
  moveHop,
  moveLoaf,
  moveNapCurl,
  movePounce,
  moveSit,
  moveStretch,
  moveTrot,
  moveWalk,
  moveZoomies,
  movePipeLounge,
  moveTowerPerch,
  moveTunnelDash,
  moveProwl,
]
export const WORLDS: readonly World[] = [
  worldBackyard,
  worldRooftops,
  worldBeachPier,
  worldNeonAlley,
  worldSnowyCabin,
  worldSpaceStation,
]
export const NAMED_CATS: readonly NamedCat[] = [
  catCaptainWhiskers,
  catAdmiralClaw,
  catBoo,
  catMerlinMeow,
  catNova,
  catPixel,
]
