// Generated by tools/build-content.mjs: add a file to a content folder, then rerun it.
import breedGinger from './breeds/ginger'
import breedTabby from './breeds/tabby'
import breedGrey from './breeds/grey'
import breedBlack from './breeds/black'
import breedWhite from './breeds/white'
import breedCream from './breeds/cream'
import breedCalico from './breeds/calico'
import breedTuxedo from './breeds/tuxedo'
import breedSiamese from './breeds/siamese'
import breedChocolate from './breeds/chocolate'
import breedCinnamon from './breeds/cinnamon'
import breedSilver from './breeds/silver'
import breedSmoke from './breeds/smoke'
import breedTortoiseshell from './breeds/tortoiseshell'
import breedRagdoll from './breeds/ragdoll'
import breedBengal from './breeds/bengal'
import breedLynx from './breeds/lynx'
import breedNebula from './breeds/nebula'
import moveGroom from './moves/groom'
import moveHop from './moves/hop'
import moveLoaf from './moves/loaf'
import moveNapCurl from './moves/nap-curl'
import movePounce from './moves/pounce'
import moveSit from './moves/sit'
import moveStretch from './moves/stretch'
import moveTrot from './moves/trot'
import moveWalk from './moves/walk'
import moveZoomies from './moves/zoomies'
import type { Breed, Move } from './types'

export const BREEDS: readonly Breed[] = [
  breedGinger,
  breedTabby,
  breedGrey,
  breedBlack,
  breedWhite,
  breedCream,
  breedCalico,
  breedTuxedo,
  breedSiamese,
  breedChocolate,
  breedCinnamon,
  breedSilver,
  breedSmoke,
  breedTortoiseshell,
  breedRagdoll,
  breedBengal,
  breedLynx,
  breedNebula,
]
export const MOVES: readonly Move[] = [
  moveGroom,
  moveHop,
  moveLoaf,
  moveNapCurl,
  movePounce,
  moveSit,
  moveStretch,
  moveTrot,
  moveWalk,
  moveZoomies,
]
