// Regenerates hooks/content/index.ts from the files in each content folder: node tools/build-content.mjs [--check]
// Existing entries keep their place and new files append, so seeded rolls over a registry stay stable.
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const content = join(dirname(fileURLToPath(import.meta.url)), '..', 'hooks', 'content')
const barrel = join(content, 'index.ts')
const KINDS = [
  { dir: 'breeds', list: 'BREEDS', type: 'Breed', prefix: 'breed' },
  { dir: 'moves', list: 'MOVES', type: 'Move', prefix: 'move' },
  { dir: 'worlds', list: 'WORLDS', type: 'World', prefix: 'world' },
  { dir: 'cats', list: 'NAMED_CATS', type: 'NamedCat', prefix: 'cat' },
  { dir: 'reactions', list: 'REACTIONS', type: 'Reaction', prefix: 'reaction' },
  { dir: 'interactions', list: 'INTERACTIONS', type: 'Interaction', prefix: 'interaction' },
  { dir: 'expeditions', list: 'EXPEDITIONS', type: 'Expedition', prefix: 'expedition' },
  { dir: 'quests', list: 'QUESTS', type: 'Quest', prefix: 'quest' },
  { dir: 'events', list: 'EVENTS', type: 'GameEvent', prefix: 'event' },
  { dir: 'skills', list: 'SKILL_FILES', type: 'SkillSpec', prefix: 'skill' },
  { dir: 'furniture', list: 'FURNITURE', type: 'FurnitureSpec', prefix: 'furniture' },
  { dir: 'shop', list: 'SHOP', type: 'ShopItem', prefix: 'shop' },
  { dir: 'materials', list: 'MATERIALS', type: 'Material', prefix: 'material' },
  { dir: 'behaviors', list: 'BEHAVIORS', type: 'Behavior', prefix: 'behavior' },
  { dir: 'goals', list: 'GOALS', type: 'Goal', prefix: 'goal' },
  { dir: 'speech', list: 'SPEECH', type: 'Speech', prefix: 'speech' },
]
const isCheck = process.argv.includes('--check')

const previous = existsSync(barrel) ? readFileSync(barrel, 'utf8') : ''
const problems = []
const camel = id => id.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase())
// The id property of the `export default defineX({...})` object, ignoring comments, strings and nested objects.
const exportedId = source => {
  const start = source.search(/export default\s+define\w+\(\s*\{/)
  if (start < 0) return null
  let depth = 0
  for (let i = source.indexOf('{', start); i < source.length; i++) {
    const ch = source[i]
    if (ch === '/' && source[i + 1] === '/') i = source.indexOf('\n', i) < 0 ? source.length : source.indexOf('\n', i)
    else if (ch === '/' && source[i + 1] === '*') i = source.indexOf('*/', i + 2) + 1 || source.length
    else if (ch === "'" || ch === '"' || ch === '`') {
      for (i++; i < source.length && source[i] !== ch; i++) if (source[i] === '\\') i++
    } else if (ch === '{' || ch === '[' || ch === '(') depth++
    else if (ch === '}' || ch === ']' || ch === ')') { if (--depth === 0) return null }
    else if (depth === 1 && /[\s{,]/.test(source[i - 1])) {
      const m = /^id\s*:\s*(['"])([^'"]*)\1/.exec(source.slice(i))
      if (m) return m[2]
    }
  }
  return null
}
const sections = KINDS.map(kind => {
  const files = (existsSync(join(content, kind.dir)) ? readdirSync(join(content, kind.dir)) : []).filter(f => f.endsWith('.ts') && !f.endsWith('.test.ts'))
    .map(f => f.slice(0, -3))
  for (const id of files) {
    if (!/^[a-z][a-z0-9-]*$/.test(id)) problems.push(`${kind.dir}/${id}.ts: file names must be lowercase kebab-case`)
    const source = readFileSync(join(content, kind.dir, `${id}.ts`), 'utf8')
    const exported = exportedId(source)
    if (exported === null) problems.push(`${kind.dir}/${id}.ts: needs \`export default define…({ id: '${id}', … })\``)
    else if (exported !== id) problems.push(`${kind.dir}/${id}.ts: its id '${exported}' must match the file name`)
  }
  const kept = [...previous.matchAll(new RegExp(`from '\\./${kind.dir}/([a-z0-9-]+)'`, 'g'))].map(m => m[1])
    .filter(id => files.includes(id))
  const order = [...kept, ...files.filter(id => !kept.includes(id)).sort()]
  const name = id => kind.prefix + camel(id)[0].toUpperCase() + camel(id).slice(1)
  return {
    imports: order.map(id => `import ${name(id)} from './${kind.dir}/${id}'`),
    list: `// ${kind.dir} definitions in pinned order; engines apply runtime eligibility.\nexport const ${kind.list}: readonly ${kind.type}[] = [\n${order.map(id => `  ${name(id)},`).join('\n')}\n]`,
  }
})
if (problems.length) {
  console.error(problems.join('\n'))
  process.exit(1)
}
const next = ['// Generated by tools/build-content.mjs: add a file to a content folder, then rerun it.',
  ...sections.flatMap(s => s.imports), `import type { ${KINDS.map(k => k.type).join(', ')} } from './types'`, '',
  ...sections.map(s => s.list), ''].join('\n')
// Browser sprites need only breeds; keep other game registries out of the arcade dependency graph.
const breedBarrel = join(content, 'breed-registry.ts')
const breeds = ['// Generated by tools/build-content.mjs; browser-safe breed registry.', ...sections[0].imports, "import type { Breed } from './types'", '', sections[0].list, ''].join('\n')
if (isCheck) {
  if (next !== previous || !existsSync(breedBarrel) || readFileSync(breedBarrel, 'utf8') !== breeds) {
    console.error('content registries are stale: run node tools/build-content.mjs')
    process.exit(1)
  }
  console.log('hooks/content/index.ts is up to date')
} else {
  writeFileSync(barrel, next)
  writeFileSync(breedBarrel, breeds)
  console.log(`wrote hooks/content/index.ts (${KINDS.map(k => k.list).join(', ')})`)
}
