// Regenerates hooks/content/index.ts from the files in each content folder: node tools/build-content.mjs [--check]
// Existing entries keep their place and new files append, so seeded rolls over a registry stay stable.
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const content = join(dirname(fileURLToPath(import.meta.url)), '..', 'hooks', 'content')
const barrel = join(content, 'index.ts')
const KINDS = [
  { dir: 'breeds', list: 'BREEDS', type: 'Breed', prefix: 'breed' },
  { dir: 'moves', list: 'MOVES', type: 'Move', prefix: 'move' },
  { dir: 'worlds', list: 'WORLDS', type: 'World', prefix: 'world' },
]
const isCheck = process.argv.includes('--check')

const previous = existsSync(barrel) ? readFileSync(barrel, 'utf8') : ''
const problems = []
const camel = id => id.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase())
const sections = KINDS.map(kind => {
  const files = readdirSync(join(content, kind.dir)).filter(f => f.endsWith('.ts') && !f.endsWith('.test.ts'))
    .map(f => f.slice(0, -3))
  for (const id of files) {
    if (!/^[a-z][a-z0-9-]*$/.test(id)) problems.push(`${kind.dir}/${id}.ts: file names must be lowercase kebab-case`)
    const source = readFileSync(join(content, kind.dir, `${id}.ts`), 'utf8')
    if (!source.includes(`id: '${id}'`)) problems.push(`${kind.dir}/${id}.ts: its id must match the file name`)
    if (!source.includes('export default')) problems.push(`${kind.dir}/${id}.ts: needs a default export`)
  }
  const kept = [...previous.matchAll(new RegExp(`from '\\./${kind.dir}/([a-z0-9-]+)'`, 'g'))].map(m => m[1])
    .filter(id => files.includes(id))
  const order = [...kept, ...files.filter(id => !kept.includes(id)).sort()]
  const name = id => kind.prefix + camel(id)[0].toUpperCase() + camel(id).slice(1)
  return {
    imports: order.map(id => `import ${name(id)} from './${kind.dir}/${id}'`),
    list: `export const ${kind.list}: readonly ${kind.type}[] = [\n${order.map(id => `  ${name(id)},`).join('\n')}\n]`,
  }
})
if (problems.length) {
  console.error(problems.join('\n'))
  process.exit(1)
}
const next = ['// Generated by tools/build-content.mjs: add a file to a content folder, then rerun it.',
  ...sections.flatMap(s => s.imports), `import type { ${KINDS.map(k => k.type).join(', ')} } from './types'`, '',
  ...sections.map(s => s.list), ''].join('\n')
if (isCheck) {
  if (next !== previous) {
    console.error('hooks/content/index.ts is stale: run node tools/build-content.mjs')
    process.exit(1)
  }
  console.log('hooks/content/index.ts is up to date')
} else {
  writeFileSync(barrel, next)
  console.log(`wrote hooks/content/index.ts (${KINDS.map(k => k.list).join(', ')})`)
}
